/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.accountmanager;
import java.awt.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author wojte
 */
public class EditAccFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddNewAccFrame
     */
    public EditAccFrame() {
        initComponents();
        initCustomVar();
    }
    public void initCustomVar(){
        String[] prevData = (String[])DataStore.getInstance().getSharedData();
        DataStore.getInstance().setSharedData(null);
        this.prevPlatform = (String) prevData[0];
        this.prevLogin = (String) prevData[1];
        this.prevPassword = (String) prevData[2];
        this.prevRank = (String) prevData[3];
        loginTextField.setText(prevLogin);
        passwordTextField.setText(prevPassword);
        platformTextField.setText(prevPlatform);
        rankTextField.setText(prevRank);
    };
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JLayeredPane();
        header = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        footer = new javax.swing.JLayeredPane();
        addCancelButton = new javax.swing.JButton();
        addSubmitButton = new javax.swing.JButton();
        loginTextField = new javax.swing.JTextField();
        passwordTextField = new javax.swing.JTextField();
        platformTextField = new javax.swing.JTextField();
        rankTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        background.setOpaque(true);

        header.setBackground(new java.awt.Color(102, 0, 204));
        header.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        header.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Unispace", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Edit Account");

        header.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        footer.setBackground(new java.awt.Color(102, 0, 204));
        footer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        footer.setOpaque(true);

        addCancelButton.setFont(new java.awt.Font("Unispace", 3, 18)); // NOI18N
        addCancelButton.setForeground(new java.awt.Color(0, 0, 0));
        addCancelButton.setText("Cancel");
        addCancelButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCancelButtonActionPerformed(evt);
            }
        });

        addSubmitButton.setFont(new java.awt.Font("Unispace", 3, 18)); // NOI18N
        addSubmitButton.setForeground(new java.awt.Color(0, 0, 0));
        addSubmitButton.setText("Confirm");
        addSubmitButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSubmitButtonActionPerformed(evt);
            }
        });

        footer.setLayer(addCancelButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        footer.setLayer(addSubmitButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(addCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(addSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        loginTextField.setBackground(new java.awt.Color(204, 204, 204));
        loginTextField.setFont(new java.awt.Font("Unispace", 2, 16)); // NOI18N
        loginTextField.setForeground(new java.awt.Color(0, 0, 0));
        loginTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        loginTextField.setNextFocusableComponent(passwordTextField);

        passwordTextField.setBackground(new java.awt.Color(204, 204, 204));
        passwordTextField.setFont(new java.awt.Font("Unispace", 2, 16)); // NOI18N
        passwordTextField.setForeground(new java.awt.Color(0, 0, 0));
        passwordTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordTextField.setNextFocusableComponent(rankTextField);
        passwordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextFieldActionPerformed(evt);
            }
        });

        platformTextField.setBackground(new java.awt.Color(204, 204, 204));
        platformTextField.setFont(new java.awt.Font("Unispace", 3, 16)); // NOI18N
        platformTextField.setForeground(new java.awt.Color(0, 0, 0));
        platformTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        platformTextField.setNextFocusableComponent(loginTextField);

        rankTextField.setBackground(new java.awt.Color(204, 204, 204));
        rankTextField.setFont(new java.awt.Font("Unispace", 2, 16)); // NOI18N
        rankTextField.setForeground(new java.awt.Color(0, 0, 0));
        rankTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rankTextField.setNextFocusableComponent(addSubmitButton);

        background.setLayer(header, javax.swing.JLayeredPane.DEFAULT_LAYER);
        background.setLayer(footer, javax.swing.JLayeredPane.DEFAULT_LAYER);
        background.setLayer(loginTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        background.setLayer(passwordTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        background.setLayer(platformTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        background.setLayer(rankTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(header))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(platformTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(loginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(rankTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(footer))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(platformTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(loginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(rankTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCancelButtonActionPerformed
        ThreadControl.getInstance().setStatus(false);
        DataStore.getInstance().setSharedData(null);
        System.out.println(false);
        this.dispose();
    }//GEN-LAST:event_addCancelButtonActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        this.currMousePressedCord = evt.getPoint();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        Point currCord = evt.getLocationOnScreen();
        this.setLocation(currCord.x - currMousePressedCord.x, currCord.y - currMousePressedCord.y);
    }//GEN-LAST:event_formMouseDragged

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        this.requestFocusInWindow();
    }//GEN-LAST:event_formWindowGainedFocus

    private void addSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSubmitButtonActionPerformed
            String loginS = loginTextField.getText();
            String passwordS = passwordTextField.getText();
            String platformS = platformTextField.getText();
            String rankS = rankTextField.getText();
            
            String DataTable[] = new String[]{platformS,loginS,passwordS,rankS};
            DataStore.getInstance().setSharedData(DataTable);
            
            dispose();
    }//GEN-LAST:event_addSubmitButtonActionPerformed

    private void passwordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditAccFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditAccFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditAccFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditAccFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditAccFrame().setVisible(true);
            }
        });
    }
    private String prevLogin;
    private String prevPassword;
    private String prevPlatform;
    private String prevRank;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCancelButton;
    private javax.swing.JButton addSubmitButton;
    private javax.swing.JLayeredPane background;
    private javax.swing.JLayeredPane footer;
    private javax.swing.JLayeredPane header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField loginTextField;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JTextField platformTextField;
    private javax.swing.JTextField rankTextField;
    // End of variables declaration//GEN-END:variables
    private Point currMousePressedCord;
}
